fieldLayouts:
  3b0d52f9-fde2-4961-9ee9-21081c8fd14f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: variantAttributeOptionValues
hasTitleField: true
name: 'Variant Attribute Option Values'
section: f47b5d82-4a50-477f-ad2f-443ae47081bd # Variant Attribute Option Values
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
