fieldLayouts:
  a1fd9c3d-0016-427f-aa91-d02064e516db:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: variantAttributeOptionLabels
hasTitleField: true
name: 'Variant Attribute Option Labels'
section: e914662f-e3a4-4810-91ed-e04260392fe6 # Variant Attribute Option Labels
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
