contentColumnType: text
fieldGroup: a57552c9-a0b8-48b6-9660-8c3fc37bf393 # Text
handle: address1
instructions: ''
name: Adres
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
