contentColumnType: string
fieldGroup: 6dc4edf0-e40f-4e8c-ab5c-3b4328e4566a # Elements (entries, categories, products, ...)
handle: images
instructions: ''
name: Afbeelding(en)
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: false
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:edcf43a4-b752-41fb-a84c-709e38f101b6' # Site Beelden
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:edcf43a4-b752-41fb-a84c-709e38f101b6' # Site Beelden
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:edcf43a4-b752-41fb-a84c-709e38f101b6' # Site Beelden
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
