contentColumnType: text
fieldGroup: b0d5e2e2-02a6-4caa-b69c-37ada293280a # Third Party
handle: seo
instructions: ''
name: SEO
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookTabEnabled: ''
  generalEnabledFields:
    - seoTitle
    - siteNamePosition
    - seoDescription
    - seoImage
  generalTabEnabled: '1'
  sitemapTabEnabled: ''
  twitterTabEnabled: ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
