enableVersioning: true
handle: locations
name: 'Winkel(s) Openingsuren'
propagationMethod: all
siteSettings:
  c1cd6425-80af-4c42-b03f-8c0eaf604c28: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 61fe404b-bad4-4408-947b-b85a87e0ed55
type: structure
