enableVersioning: true
handle: pages
name: 'Pagina''s'
propagationMethod: all
siteSettings:
  c1cd6425-80af-4c42-b03f-8c0eaf604c28: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: _pages/entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 166b0f85-4c5e-4955-81b4-dd0334bacde2
type: structure
