enableVersioning: true
handle: pickupRules
name: 'Ophaal Validatie Regels'
propagationMethod: all
siteSettings:
  c1cd6425-80af-4c42-b03f-8c0eaf604c28: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
