#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [[ $1 == "combell" ]]; then
# echo Update pushed to branch $1 $current_branch
nitro npm run build
git add www/dist
git commit -m "vite build in pre-push githook"
git push
fi
